bistroselect/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'foods/tag' => 'foods#tag'
  get 'foods/top' => 'foods#top'

  resources :users, only: [:show]

  resources :foods 

  root 'foods#top'

 
  
  
end

bistroselect/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bistroselect/app/models/food.rb
class Food < ApplicationRecord
    has_many :food_tag_relations, dependent: :destroy
    has_many :tags, through: :food_tag_relations, dependent: :destroy
    has_one_attached :image_top
  has_many_attached :images
 belongs_to :user 

 validates :image_top, :images, content_type: { in: %w[image/jpeg image/gif image/png],
                                   message: "must be a valid image format" },
                                size: { less_than: 5.megabytes,    
                                        message: "should be less than 5MB" }
                                        def resize_image_top
                                            image_top.variant(resize_to_limit: [500, 200])
                                          end
end

bistroselect/app/models/food_tag_relation.rb
class FoodTagRelation < ApplicationRecord
  belongs_to :food
  belongs_to :tag


end

bistroselect/app/models/tag.rb
class Tag < ApplicationRecord
    has_many :food_tag_relations, dependent: :destroy
    has_many :foods, through: :food_tag_relations, dependent: :destroy
end

bistroselect/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods
  
  has_many :foods, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }
end

bistroselect/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
end

end

bistroselect/app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
        @foods = Food.all
        if params[:tag_ids]
          @foods = []
          params[:tag_ids].each do |key, value|
            if value == "1"
              tag_foods = Tag.find_by(name: key).foods
              @foods = @foods.empty? ? tag_foods : @foods & tag_foods
            end
          end
        end

        if params[:tag]
          Tag.create(name: params[:tag])
        end
    end
    
    def top
    end

    def new
        @food = Food.new
      end
    
      def create
        food = Food.new(food_params)
        food.user_id = current_user.id
        if food.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
    
      def show
        @food = Food.find(params[:id])
        
      end

      def edit
        @food = Food.find(params[:id])
      end

      def update
        food = Food.find(params[:id])
        if food.update(food_params)
          redirect_to :action => "show", :id => food.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        food = Food.find(params[:id])
        food.destroy
        redirect_to action: :index
      end

      def tag
        @foods = []
        if params[:tag_ids]
          params[:tag_ids].each do |value|
            tag_foods = Tag.find(value.to_i).foods
            @foods = @foods.empty? ? tag_foods : @foods & tag_foods
          end
        end
      end

      private

      def food_params
        params.require(:food).permit(:name, :food_genre, :address, :about, :image, :bistro_genre, :lat, :lng, :image_top, images: [], tag_ids: [])
      end
    end

bistroselect/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      end
end

bistroselect/app/helpers/application_helper.rb
module ApplicationHelper
end

bistroselect/app/helpers/foods_helper.rb
module FoodsHelper
end

bistroselect/app/helpers/users_helper.rb
module UsersHelper
end

bistroselect/app/views/foods/edit.html.erb
<div class="food">
<%= form_for @food do |f| %>
    <%= f.label :name %>
    
    <%= f.text_field :name, :size => 140 %> 
  

    <br>
    <%= f.label :food_genre %>
    <%= f.select :genre, 
  [["和食", "和食"], 
  ["中華", "中華"], 
  ["イタリアン", "イタリアン"]], include_blank: "選択して下さい" %>
   

    <br>
    <%= f.label :address %>
    <%= f.text_field :address, :size => 140 %> 
   

    <br>
    <%= f.label :about %>
    <%= f.text_field :about, :size => 140 %> 
    

    <br>
    <span class="image-top">
      <%= f.label :image_top, '画像' %>
      <%= f.file_field :image_top, accept: "image/jpeg,image/gif,image/png" %>
    </span>
    <script type="text/javascript">
      $("#food_image_top, #food_images").bind("change", function() {
      var size_in_megabytes = this.files[0].size/1024/1024;
      if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
      $("#food_image_top").val(""); }});
    </script>
  

    <br>
    <%= f.label :bistro_genre %>
    <%= f.select :bistro_genre, 
     [["定食屋", "定食屋"], 
     ["レストラン", "レストラン"], 
     ["居酒屋", "居酒屋"],
     ["カフェ", "カフェ"]], include_blank: "選択して下さい" %>
   <br><br>
   
   <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
    <div class='form-check'>
        <%= tag.label class: 'form-check-label' do %>
            <%= tag.check_box class: 'form-check-input' %>
            <%= tag.text %>
            <% end %>
            </div>
            <% end %>

   <%= f.label :lat,"緯度" %>
      <%= f.text_field :lat,:value =>"緯度", id: :lat %>
      <%= f.label :lng,"経度" %>
      <%= f.text_field :lng,:value =>"経度", id: :lng %>

            
   <%= f.submit "編集する" %>

   <% end %>
</div>

bistroselect/app/views/foods/index.html.erb
<h3>写真から探す</h3>


<div class="foods-container">
 <div class="top">
  <%= link_to "TOPへ", root_path %>
 </div>
 <div class="food-content">
  <% @foods.each do |t| %>
     <div class="food">
      <div class="food-a">
       <%= image_tag t.resize_image_top if t.image_top.attached? %>
       <br>
       <p><%= t. name%></p>
      </div>
      <div class="food-b">
       <li><%= link_to "詳細", food_path(t.id) %></li>
       <li><%= link_to "編集", edit_food_path(t.id) %></li>
       <li><%= link_to "削除", food_path(t.id), method: :delete %></li>
      </div>
     </div>
  <% end %>
   </div>
</div>





 

bistroselect/app/views/foods/new.html.erb
<h3>お店を投稿する</h3>
<div class=new>
  <div class="top">
   <%= link_to "TOPへ", root_path %>
  </div>

 <%= form_for @food do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :size => 30 %>
  </div>

  <div class="field">
   <%= f.label :food_genre  %>
   <%= f.select :genre, 
   [["和食", "和食"], 
   ["中華", "中華"], 
   ["イタリアン", "イタリアン"]], include_blank: "選択して下さい" %>
  </div>

  <div class="field">
   <%= f.label :address %>
   <%= f.text_field :address, :size => 30 %>
  </div>

  <div class="field">
   <%= f.label :about  %>
   <%= f.text_area :about, :size => "30x2" %>
  </div>

  
  <div class="field">
 
    <span class="image-top">
      <%= f.label :image_top, 'Photo' %>
      <%= f.file_field :image_top, accept: "image/jpeg,image/gif,image/png" %>
    </span>
    <script type="text/javascript">
      $("#food_image_top, #food_images").bind("change", function() {
      var size_in_megabytes = this.files[0].size/1024/1024;
      if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
      $("#food_image_top").val(""); }});
    </script>
  </div>

  <div class="field">
   <%= f.label :bistro_genre  %>
   <%= f.select :bistro_genre, 
    [["定食屋", "定食屋"], 
    ["レストラン", "レストラン"], 
    ["居酒屋", "居酒屋"],
    ["カフェ", "カフェ"]], include_blank: "選択して下さい" %>
  </div>

  <div class='form-group'>
   <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
    <div class='form-check'>
        <%= tag.label class: 'form-check-label' do %>
            <%= tag.check_box class: 'form-check-input' %>
            <%= tag.text %>
        <% end %>
    </div>
   <% end %>
  </div>
 <% end %>



<div class="field">
Map
</div>

<input id="address" type="textbox" value="">
<input type="button" value="検索" onclick="codeAddress()">
<p>マーカーをドラック＆ドロップで位置の調整ができます。<p>
<%= form_for @food do |f| %>
  <div class=form-group>
   <%= f.label :lat,"緯度" %>
     <%= f.text_field :lat,:value =>"緯度", id: :lat %>
     <%= f.label :lng,"経度" %>
     <%= f.text_field :lng,:value =>"経度", id: :lng %>
 
   <%= f.submit "投稿する" %>
  </div>
 <% end %>
<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: 35.6803997, lng:139.7690174},  //東京
    zoom: 15,
    
  });
}

//検索後のマップ作成
let geocoder
let aft
function codeAddress(){
  let inputAddress = document.getElementById('address').value;
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
        //マーカーが複数できないようにする
        if (aft == true){
            marker.setMap(null);
        }

        //新しくマーカーを作成する
        map.setCenter(results[0].geometry.location);
            marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location,
            draggable: true	// ドラッグ可能にする
            });

            //二度目以降か判断
            aft = true
    
            //検索した時に緯度経度を入力する
            document.getElementById('lat').value = results[0].geometry.location.lat();
            document.getElementById('lng').value = results[0].geometry.location.lng();
    
            // マーカーのドロップ（ドラッグ終了）時のイベント
            google.maps.event.addListener( marker, 'dragend', function(ev){
                // イベントの引数evの、プロパティ.latLngが緯度経度
                document.getElementById('lat').value = ev.latLng.lat();
                document.getElementById('lng').value = ev.latLng.lng();
            });
        } else {
          alert('該当する結果がありませんでした：' + status);
        }
      });   
    }
    
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDN1Mp6wqIolbGWzvyJGwvumdqUgesl8jI&callback=initMap" async defer></script>

    <%= link_to "一覧に戻る", foods_path %>
    <br>
    <br>
    <br>
</div>

bistroselect/app/views/foods/show.html.erb
<h3>詳細</h3>
<div class="food">
  <p><%= @food.name %></p>
  <p><%= @food.genre %></p>
  <p><%= @food.about %></p>
     <%= image_tag @food.resize_image_top if @food.image_top.attached? %>
  <p><%= @food.bistro_genre %></p>
  <p><%= @food.created_at %></p>
  <p><%= @food.user.email %></p> 
     <% @food.tags.each do |tag| %>
       <span><%= tag.name %></span>
     <% end %>
  <div id='map'>
</div>

<style>
#map {
  height: 600px;
  width: 100%;
}
</style>

<!-- js部分 -->
<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: <%= @food.lat %>, lng: <%= @food.lng %>},
    zoom: 15,
  });

   marker = new google.maps.Marker({
    position:  {lat: <%= @food.lat %>, lng: <%= @food.lng %>},
    map: map
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GMAP_API'] %>&callback=initMap" async defer></script>　
</div>


<%= link_to "一覧に戻る", foods_path %>
<%= link_to "編集する", edit_food_path(@food.id) %>

<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 100%;
}
</style>

<!-- js部分 -->
<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: <%= @food.lat %>, lng: <%= @food.lng %>},
    zoom: 15,
  });

   marker = new google.maps.Marker({
    position:  {lat: <%= @food.lat %>, lng: <%= @food.lng %>},
    map: map
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDN1Mp6wqIolbGWzvyJGwvumdqUgesl8jI&callback=initMap" async defer></script>

bistroselect/app/views/foods/tag.html.erb
<div class=tag>
 <div class=tag-title>
  タグ検索
 </div>

 <div class=tag-top>
  <%= link_to "TOPへ", root_path %>
 </div>

 <div class=tag-a>
  <%= form_tag({ controller: "foods", action: "tag" }, method: :get) do %>
    <% Tag.all.each do |t| %>
        <li><%= check_box_tag 'tag_ids[]', t.id %><%= t.name %></li>
    <% end %>
    <%= submit_tag '検索' %>
  <% end %>

  <%= form_tag({controller:"foods",action:"tag"}, method: :get) do %>
    <%= text_field_tag :tag %>
    <%= submit_tag 'タグを追加' %>
    <br>
    <br>
    <br>
  <% end %>

  <% @foods.each do |food| %>
    <p><%= food.name %></p>
  <% end %>
 <div/>
</div>

bistroselect/app/views/foods/top.html.erb
<body>
<%= image_tag 'top.jpg', class:"top-image" %>


 <div class= "container">
  
 <br>
  <div class= "content">
   <%= link_to '写真から探す', :controller => "foods", :action => "index" %>
  </div>

  <br>
 <div class= "content">
  <%= link_to 'タグから探す', :controller => "foods", :action => "tag" %>
 </div>

  <br>
 <div class= "content">
  <%= link_to "お店を投稿する", new_food_path %>
 </div>

</body>

bistroselect/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bistroselect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
     <h1>Bistro select</h1>
     <ul>
       <% if user_signed_in? %>
       <li><%= link_to "マイページへ", user_path(current_user.id) %></li>
       <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
       <% else %>
       <li><%= link_to "ログイン", new_user_session_path %></li>
       <li><%= link_to "新規登録", new_user_registration_path %></li>
       <% end %>
     </ul>
   </header>
   <main>
      <%= yield %>
    </main>
 
    <footer>
     <p>Copyright © GeekSalon All Rights Reserved.</p>
    </footer>

   </body>
</html>

bistroselect/app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

bistroselect/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

bistroselect/app/views/users/show.html.erb
<h1>マイページ</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.foods.each do |t| %>
  <%= t.user.name %>
  <%= t.name %>
<% end %>

<%= link_to "一覧に戻る", foods_path %>